#!/bin/bash
#SBATCH --export=NONE
#SBATCH --get-user-env 
#SBATCH -o /home/hpc/tb601/ga94rac2/DropSeq.%j
#SBATCH -D /home/hpc/tb601/ga94rac2
#SBATCH -J DropSeq
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=gildas.lepennetier@tum.de
#SBATCH --time=30:00:00 
#SBATCH --nodes=1

#SBATCH --clusters=mpp2

### MPP2 should be enough: 64 Go RAM, 28 core / Node
## mail: NONE, BEGIN, END, FAIL, REQUEUE, ALL

# sbatch SUBMIT.sub --dependency=after:xxx

echo "###### LOADING MODULES"
source /etc/profile.d/modules.sh
####module load python/3.3_anaconda_nompi
module load python/2.7_anaconda_nompi

# load module for QC
module load java/1.8

	# FastQC
	#bash /home/hpc/tb601/ga94rac2/dropseqpipeline/RUN.2.FastQC.sh /home/hpc/tb601/ga94rac2/dropseqpipeline/PARAMETERS_cluster.sh

	# Run dropseq_old
	#bash /home/hpc/tb601/ga94rac2/dropseqpipeline/RUN.3.sh /home/hpc/tb601/ga94rac2/dropseqpipeline/PARAMETERS_cluster.sh

 # Run Dropseq try
bash /home/hpc/tb601/ga94rac2/dropseqpipeline/RUN.3_dissected_piped.sh /home/hpc/tb601/ga94rac2/dropseqpipeline/PARAMETERS_cluster.sh
